# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myitems.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'myitems.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmyitems.proto\x12\x07myitems\"\x1f\n\rItemIdRequest\x12\x0e\n\x06itemId\x18\x01 \x01(\x05\",\n\x08ItemInfo\x12\x0e\n\x06itemId\x18\x01 \x01(\x05\x12\x10\n\x08itemName\x18\x02 \x01(\t\"#\n\x0fItemNameRequest\x12\x10\n\x08itemName\x18\x01 \x01(\t\"2\n\x16\x41\x64\x64ItemsMethodResponse\x12\x18\n\x10numberItemsAdded\x18\x01 \x01(\x05\"\x1e\n\x0b\x43hatMessage\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xc7\x02\n\x0bItemService\x12\x38\n\x0bGetItemById\x12\x16.myitems.ItemIdRequest\x1a\x11.myitems.ItemInfo\x12\x33\n\x0cListAllItems\x12\x0e.myitems.Empty\x1a\x11.myitems.ItemInfo0\x01\x12G\n\x08\x41\x64\x64Items\x12\x18.myitems.ItemNameRequest\x1a\x1f.myitems.AddItemsMethodResponse(\x01\x12@\n\x0e\x43hatAboutItems\x12\x14.myitems.ChatMessage\x1a\x14.myitems.ChatMessage(\x01\x30\x01\x12>\n\x16\x41\x64\x64ItemPerformanceTest\x12\x11.myitems.ItemInfo\x1a\x11.myitems.ItemInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myitems_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMIDREQUEST']._serialized_start=26
  _globals['_ITEMIDREQUEST']._serialized_end=57
  _globals['_ITEMINFO']._serialized_start=59
  _globals['_ITEMINFO']._serialized_end=103
  _globals['_ITEMNAMEREQUEST']._serialized_start=105
  _globals['_ITEMNAMEREQUEST']._serialized_end=140
  _globals['_ADDITEMSMETHODRESPONSE']._serialized_start=142
  _globals['_ADDITEMSMETHODRESPONSE']._serialized_end=192
  _globals['_CHATMESSAGE']._serialized_start=194
  _globals['_CHATMESSAGE']._serialized_end=224
  _globals['_EMPTY']._serialized_start=226
  _globals['_EMPTY']._serialized_end=233
  _globals['_ITEMSERVICE']._serialized_start=236
  _globals['_ITEMSERVICE']._serialized_end=563
# @@protoc_insertion_point(module_scope)
